### ISSUE TITLE
polymer support

### ISSUE THREAD

**Issue by mmmmmmmmmmmmmmmmaly** [u-lumaa/BackroomsMod#6]
I know it is not a bug report but a feature request
https://modrinth.com/mod/polymer

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
https://modrinth.com/mod/server_mobs_api

**Comment by u-lumaa** [comment]
Our mod isn't meant to be only server-side

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
sorry
