### ISSUE TITLE
Building Current Version Myself

### ISSUE THREAD

**Issue by AnonymouseCow** [u-lumaa/BackroomsMod#9]
Is it possible to build from the command line? I am trying to use ./gradlew build however I get a bunch of errors saying:
`error: package software.bernie.geckolib.core.manager does not exist`
All of which are in the BacteriaEntity/BacteriaRenderer.

May I ask what I should do to build the mod?

Thanks and sorry if I am missing something obvious with how I am trying to do this.

**Comment by u-lumaa** [comment]
You totally can build the current version by yourself, what we did ourselves temporarily is "deactivating" the file, 
You change the name of all the `Bacteria[...].java` and you add `.disabled`
You can optionally remove the GeckoLib package as it's not used
You will have to remove some code about that Bacteria thing and you should be good to go

If there are any other issues, let us know
